# Generated by Django 4.1 on 2022-10-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
